[package]
name = "spellit"
version = "0.2.0"
authors = ["Kafji <k@kafji.net>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
clap = "2.33"
dotenv_codegen = "0.15"

[dev-dependencies]
assert_cmd = "1.0"
predicates = "1.0"
